FROM nginx:1.23.1

ARG LISTEN_PORT
ENV LISTEN_PORT=$LISTEN_PORT
ARG SERVER_NAME_EN
ENV SERVER_NAME_EN=$SERVER_NAME_EN
ARG REDIRECT_NAME_EN
ENV REDIRECT_NAME_EN=$REDIRECT_NAME_EN
ARG SERVER_NAME_FR
ENV SERVER_NAME_FR=$SERVER_NAME_FR
ARG REDIRECT_NAME_FR
ENV REDIRECT_NAME_FR=$REDIRECT_NAME_FR

COPY default.conf.template /etc/nginx/templates/default.conf.template
