name: Dynamic Application Security Tests

on:
  push:
    branches: [main]

jobs:
  zap-proxy-scan:
    name: ZAP Proxy Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Docker Build
        run: docker build --build-arg LISTEN_PORT=${{ secrets.LISTEN_PORT }} --build-arg SERVER_NAME_EN=${{ secrets.SERVER_NAME_EN }} --build-arg SERVER_NAME_FR=${{ secrets.SERVER_NAME_FR }} --build-arg  REDIRECT_NAME_EN=${{ secrets.REDIRECT_NAME_EN }} --build-arg REDIRECT_NAME_FR=${{ secrets.REDIRECT_NAME_FR }} -t c19-benefits-finder-redirect .
        env:
          CI: true

      - name: Docker run
        run: docker run -d -p 8080:80 c19-benefits-finder-redirect
        env:
          CI: true

      - name: OWASP ZAP FULL Scan
        uses: zaproxy/action-full-scan@v0.3.0
        with:
          target: "http://localhost:8080"
          fail_action: "false"
          token: ${{ secrets.GITHUB_TOKEN }}
