name: Unit Tests

on:
  pull_request:

jobs:
  unit:
    name: Nginx Config File Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🔔
        uses: actions/checkout@v3

      - name: Docker Build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: false
          tags: c19-benefits-finder-redirect
          build-args: |
            LISTEN_PORT: ${{ secrets.LISTEN_PORT }}
            SERVER_NAME_EN: ${{ secrets.SERVER_NAME_EN }}
            SERVER_NAME_FR: ${{ secrets.SERVER_NAME_FR }}
            REDIRECT_NAME_EN: ${{ secrets.REDIRECT_NAME_EN }}
            REDIRECT_NAME_FR: ${{ secrets.REDIRECT_NAME_FR }}
        env:
          CI: true

      - name: Docker run
        run: docker run -d -p 8080:80 c19-benefits-finder-redirect
        env:
          CI: true
      
      - name: Test nginx config files
        run: docker exec c19-benefits-finder-redirect nginx -t
        env:
          CI: true