name: Unit Tests

on:
  pull_request:

jobs:
  unit:
    name: Nginx Config File Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🔔
        uses: actions/checkout@v3

      - name: Docker Build
        run: docker build --build-arg LISTEN_PORT=${{ secrets.LISTEN_PORT }} --build-arg SERVER_NAME_EN=${{ secrets.SERVER_NAME_EN }} --build-arg SERVER_NAME_FR=${{ secrets.SERVER_NAME_FR }} --build-arg  REDIRECT_NAME_EN=${{ secrets.REDIRECT_NAME_EN }} --build-arg REDIRECT_NAME_FR=${{ secrets.REDIRECT_NAME_FR }} -t c19-benefits-finder-redirect .
        env:
          CI: true

      - name: Docker run
        run: docker run -d -p 8080:80 --name redirect c19-benefits-finder-redirect && docker exec redirect nginx -t 
        env:
          CI: true
      
      - name: check which containers are running
        run: docker ps -a 
        env:
          CI: true
          
      - name: check docker logs
        run: docker logs redirect 
        env:
          CI: true
      
      - name: Test nginx config files
        run: docker exec redirect nginx -t 
        env:
          CI: true